'use strict';

const { DIALECTS } = require('./dialects');

const ORDER = [
  'dropRelation', 'dropIndex', 'renameTable', 'renameColumn', 'createTable',
  'addColumn', 'modifyColumn', 'setPrimaryKey', 'dropColumn', 'dropTable',
  'addIndex', 'addRelation', 'setTableComment',
];

const esc = (s) => String(s).replace(/'/g, "''");

function indexName(table, index) {
  return index.name || 'idx_' + table + '_' + index.columns.join('_');
}

function relationName(rel) {
  return rel.name || 'fk_' + rel.fromTable + '_' + rel.fromColumns.join('_');
}

function columnDef(col, dialectKey, d, opts = {}) {
  const parts = [d.quote(col.name), col.type || d.defaultTypes.string];
  if (dialectKey === 'mssql' && col.autoIncrement && !opts.noIdentity) parts.push('IDENTITY(1,1)');
  if (col.default) parts.push('DEFAULT ' + col.default);
  if (!col.nullable) parts.push('NOT NULL');
  if (col.autoIncrement && !opts.noIdentity) {
    if (dialectKey === 'mysql') parts.push('AUTO_INCREMENT');
    else if (dialectKey === 'postgres' || dialectKey === 'oracle') parts.push('GENERATED BY DEFAULT AS IDENTITY');
  }
  if (dialectKey === 'mysql' && col.comment) parts.push("COMMENT '" + esc(col.comment) + "'");
  return parts.join(' ');
}

function commentStatements(dialectKey, d, table, col) {
  if (!col.comment) return [];
  if (dialectKey === 'postgres' || dialectKey === 'oracle') {
    return ['COMMENT ON COLUMN ' + d.quote(table) + '.' + d.quote(col.name) + " IS '" + esc(col.comment) + "';"];
  }
  if (dialectKey === 'mssql') return ['-- description of column ' + table + '.' + col.name + ': ' + col.comment];
  return [];
}

function createTableStatements(table, dialectKey, d) {
  const cols = table.columns.filter((c) => c.name.trim());
  const lines = cols.map((c) => '  ' + columnDef(c, dialectKey, d));
  const pk = cols.filter((c) => c.primaryKey).map((c) => d.quote(c.name));
  if (pk.length) lines.push('  PRIMARY KEY (' + pk.join(', ') + ')');
  const out = ['CREATE TABLE ' + d.quote(table.name) + ' (\n' + lines.join(',\n') + '\n);'];
  if (table.comment) {
    if (dialectKey === 'postgres' || dialectKey === 'oracle') {
      out.push('COMMENT ON TABLE ' + d.quote(table.name) + " IS '" + esc(table.comment) + "';");
    } else if (dialectKey === 'mysql') {
      out.push('ALTER TABLE ' + d.quote(table.name) + " COMMENT = '" + esc(table.comment) + "';");
    }
  }
  if (dialectKey === 'postgres' || dialectKey === 'oracle' || dialectKey === 'mssql') {
    for (const c of cols) out.push(...commentStatements(dialectKey, d, table.name, c));
  }
  for (const ix of table.indexes || []) {
    if (ix.columns.some((c) => c.trim())) out.push(...indexStatements('add', table.name, ix, dialectKey, d));
  }
  return out;
}

function indexStatements(action, table, index, dialectKey, d) {
  const name = indexName(table, index);
  if (action === 'add') {
    const cols = index.columns.filter((c) => c.trim()).map((c) => d.quote(c)).join(', ');
    return ['CREATE ' + (index.unique ? 'UNIQUE ' : '') + 'INDEX ' + d.quote(name) + ' ON ' + d.quote(table) + ' (' + cols + ');'];
  }
  if (dialectKey === 'mysql' || dialectKey === 'mssql') {
    return ['DROP INDEX ' + d.quote(name) + ' ON ' + d.quote(table) + ';'];
  }
  return ['DROP INDEX ' + d.quote(name) + ';'];
}

function modifyColumnStatements(ch, dialectKey, d) {
  const t = d.quote(ch.table);
  const c = ch.column;
  const q = d.quote(c.name);
  const out = [];
  if (dialectKey === 'mysql') {
    out.push('ALTER TABLE ' + t + ' MODIFY COLUMN ' + columnDef(c, dialectKey, d, { noIdentity: true }) + ';');
    return out;
  }
  if (dialectKey === 'postgres') {
    if (ch.changed.type) out.push('ALTER TABLE ' + t + ' ALTER COLUMN ' + q + ' TYPE ' + c.type + ';');
    if (ch.changed.default) {
      out.push('ALTER TABLE ' + t + ' ALTER COLUMN ' + q + (c.default ? ' SET DEFAULT ' + c.default : ' DROP DEFAULT') + ';');
    }
    if (ch.changed.nullable) {
      out.push('ALTER TABLE ' + t + ' ALTER COLUMN ' + q + (c.nullable ? ' DROP NOT NULL' : ' SET NOT NULL') + ';');
    }
    if (ch.changed.comment) out.push(...commentStatements(dialectKey, d, ch.table, c));
    return out;
  }
  if (dialectKey === 'oracle') {
    if (ch.changed.type) out.push('ALTER TABLE ' + t + ' MODIFY (' + q + ' ' + c.type + ');');
    if (ch.changed.default) out.push('ALTER TABLE ' + t + ' MODIFY (' + q + ' DEFAULT ' + (c.default || 'NULL') + ');');
    if (ch.changed.nullable) out.push('ALTER TABLE ' + t + ' MODIFY (' + q + (c.nullable ? ' NULL' : ' NOT NULL') + ');');
    if (ch.changed.comment) out.push(...commentStatements(dialectKey, d, ch.table, c));
    return out;
  }
  if (ch.changed.type || ch.changed.nullable) {
    out.push('ALTER TABLE ' + t + ' ALTER COLUMN ' + q + ' ' + c.type + (c.nullable ? ' NULL' : ' NOT NULL') + ';');
  }
  if (ch.changed.default) {
    out.push('-- changing the default of ' + ch.table + '.' + c.name + ': drop the old DEFAULT constraint and add a new one (DEFAULT ' + (c.default || 'none') + ')');
  }
  if (ch.changed.comment) out.push(...commentStatements(dialectKey, d, ch.table, c));
  return out;
}

function sqlChange(ch, dialectKey, d) {
  const t = (name) => d.quote(name);
  switch (ch.kind) {
    case 'renameTable':
      if (dialectKey === 'mysql') return ['RENAME TABLE ' + t(ch.from) + ' TO ' + t(ch.to) + ';'];
      if (dialectKey === 'mssql') return ["EXEC sp_rename '" + esc(ch.from) + "', '" + esc(ch.to) + "';"];
      return ['ALTER TABLE ' + t(ch.from) + ' RENAME TO ' + t(ch.to) + ';'];
    case 'renameColumn':
      if (dialectKey === 'mssql') return ["EXEC sp_rename '" + esc(ch.table + '.' + ch.from) + "', '" + esc(ch.to) + "', 'COLUMN';"];
      return ['ALTER TABLE ' + t(ch.table) + ' RENAME COLUMN ' + t(ch.from) + ' TO ' + t(ch.to) + ';'];
    case 'createTable':
      return createTableStatements(ch.table, dialectKey, d);
    case 'addColumn': {
      const def = columnDef(ch.column, dialectKey, d);
      const stmt = dialectKey === 'oracle'
        ? 'ALTER TABLE ' + t(ch.table) + ' ADD (' + def + ');'
        : dialectKey === 'mssql'
          ? 'ALTER TABLE ' + t(ch.table) + ' ADD ' + def + ';'
          : 'ALTER TABLE ' + t(ch.table) + ' ADD COLUMN ' + def + ';';
      return [stmt, ...(dialectKey === 'mysql' ? [] : commentStatements(dialectKey, d, ch.table, ch.column))];
    }
    case 'modifyColumn':
      return modifyColumnStatements(ch, dialectKey, d);
    case 'setPrimaryKey': {
      const out = [];
      if (ch.had) {
        if (dialectKey === 'mysql' || dialectKey === 'oracle') out.push('ALTER TABLE ' + t(ch.table) + ' DROP PRIMARY KEY;');
        else out.push('ALTER TABLE ' + t(ch.table) + ' DROP CONSTRAINT ' + t(ch.table + '_pkey') + '; -- check the primary key constraint name');
      }
      if (ch.columns.length) {
        out.push('ALTER TABLE ' + t(ch.table) + ' ADD PRIMARY KEY (' + ch.columns.map(t).join(', ') + ');');
      }
      return out;
    }
    case 'dropColumn':
      return ['ALTER TABLE ' + t(ch.table) + ' DROP COLUMN ' + t(ch.column) + ';'];
    case 'dropTable':
      return ['DROP TABLE ' + t(ch.name) + ';'];
    case 'addIndex':
      return indexStatements('add', ch.table, ch.index, dialectKey, d);
    case 'dropIndex':
      return indexStatements('drop', ch.table, ch.index, dialectKey, d);
    case 'addRelation': {
      const r = ch.relation;
      const toCols = r.toColumns.filter((c) => c.trim());
      return ['ALTER TABLE ' + t(r.fromTable) + ' ADD CONSTRAINT ' + t(relationName(r)) +
        ' FOREIGN KEY (' + r.fromColumns.map(t).join(', ') + ') REFERENCES ' + t(r.toTable) +
        (toCols.length ? ' (' + toCols.map(t).join(', ') + ')' : '') + ';'];
    }
    case 'dropRelation': {
      const r = ch.relation;
      if (!r.name) {
        return ['-- drop the foreign key ' + r.fromTable + ' (' + r.fromColumns.join(', ') + ') -> ' + r.toTable + ' (constraint name unknown)'];
      }
      if (dialectKey === 'mysql') return ['ALTER TABLE ' + t(r.fromTable) + ' DROP FOREIGN KEY ' + t(r.name) + ';'];
      return ['ALTER TABLE ' + t(r.fromTable) + ' DROP CONSTRAINT ' + t(r.name) + ';'];
    }
    case 'setTableComment':
      if (dialectKey === 'postgres' || dialectKey === 'oracle') {
        return ['COMMENT ON TABLE ' + t(ch.table) + " IS '" + esc(ch.comment) + "';"];
      }
      if (dialectKey === 'mysql') return ['ALTER TABLE ' + t(ch.table) + " COMMENT = '" + esc(ch.comment) + "';"];
      return ['-- description of table ' + ch.table + ': ' + ch.comment];
    default:
      return [];
  }
}

function mongoValue(raw) {
  const s = String(raw == null ? '' : raw).trim();
  if (s === '') return 'null';
  try {
    return JSON.stringify(JSON.parse(s));
  } catch (err) {
    return JSON.stringify(s);
  }
}

function mongoChange(ch) {
  switch (ch.kind) {
    case 'createTable':
      return ['db.createCollection(' + JSON.stringify(ch.table.name) + ');'];
    case 'dropTable':
      return ['db.' + ch.name + '.drop();'];
    case 'renameTable':
      return ['db.' + ch.from + '.renameCollection(' + JSON.stringify(ch.to) + ');'];
    case 'addColumn':
      return ['db.' + ch.table + '.updateMany({ ' + JSON.stringify(ch.column.name) + ': { $exists: false } }, { $set: { ' +
        JSON.stringify(ch.column.name) + ': ' + mongoValue(ch.column.default) + ' } });'];
    case 'dropColumn':
      return ['db.' + ch.table + '.updateMany({}, { $unset: { ' + JSON.stringify(ch.column) + ': "" } });'];
    case 'renameColumn':
      return ['db.' + ch.table + '.updateMany({}, { $rename: { ' + JSON.stringify(ch.from) + ': ' + JSON.stringify(ch.to) + ' } });'];
    case 'modifyColumn':
      if (ch.changed.type) {
        return ['// field ' + ch.table + '.' + ch.column.name + ': changing the type to "' + ch.column.type + '" needs a manual data migration'];
      }
      return [];
    case 'addIndex': {
      const keys = ch.index.columns.filter((c) => c.trim()).map((c) => JSON.stringify(c) + ': 1').join(', ');
      const opts = [];
      if (ch.index.unique) opts.push('unique: true');
      if (ch.index.name) opts.push('name: ' + JSON.stringify(ch.index.name));
      return ['db.' + ch.table + '.createIndex({ ' + keys + ' }' + (opts.length ? ', { ' + opts.join(', ') + ' }' : '') + ');'];
    }
    case 'dropIndex':
      return ['db.' + ch.table + '.dropIndex(' + JSON.stringify(indexName(ch.table, ch.index)) + ');'];
    case 'addRelation':
    case 'dropRelation':
      return ['// MongoDB has no foreign keys — document the ' + ch.relation.fromTable + ' -> ' + ch.relation.toTable + ' relation in the schema description'];
    case 'setPrimaryKey':
      return ['// the key in MongoDB is always _id — changing it means rewriting the collection'];
    case 'setTableComment':
      return [];
    default:
      return [];
  }
}

function mongoScript(changes) {
  const out = [];
  for (const ch of changes) out.push(...mongoChange(ch));
  return out.join('\n');
}

function changesToScript(changes, dialectKey) {
  const sorted = [...changes].sort((a, b) => ORDER.indexOf(a.kind) - ORDER.indexOf(b.kind));
  if (!sorted.length) return '';
  if (DIALECTS[dialectKey].kind === 'mongo') return mongoScript(sorted);
  const d = DIALECTS[dialectKey];
  const out = [];
  for (const ch of sorted) out.push(...sqlChange(ch, dialectKey, d));
  return out.join('\n');
}

function fullCreateScript(schema, dialectKey) {
  const changes = [];
  for (const table of schema.tables) {
    if (table.name.trim()) changes.push({ kind: 'createTable', table });
  }
  for (const relation of schema.relations) {
    if (relation.fromTable && relation.toTable) changes.push({ kind: 'addRelation', relation });
  }
  return changesToScript(changes, dialectKey);
}

module.exports = { changesToScript, fullCreateScript };
